### ISSUE TITLE
Remove the console errors.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#1]

**Comment by nityanandagohain** [comment]
I want to take this issue The console has errors like techradar[0] not found . I think this is occurring because the news is not fetch immediately it takes some time and until then it is null. Am I right.

**Comment by Jigar3** [comment]
I would like to work on this issue

**Comment by aswanthkoleri** [comment]
@nityanandagohain YOu may work on this !

**Comment by nityanandagohain** [comment]
![screenshot from 2018-01-12 11-12-13](https://user-images.githubusercontent.com/26831659/34861266-aa65916c-f789-11e7-8721-39f1591fd5e6.png)
Help please I have done this but after that my computer crashes when i run this , maybe the while loop is running infinite. Hints will be very helpful
