### ISSUE TITLE
Replace the news Image with the website logo if the Image is not found.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#10]

**Comment by beast02** [comment]
I would like to  work on this issue .

**Comment by aadixiiita** [comment]
I would like to work on it ..

**Comment by aswanthkoleri** [comment]
@beast02  Carry on ! :smile:

**Comment by aswanthkoleri** [comment]
@beast02  Any update ? If no update then I'll assign this issue to @aadixiiita

**Comment by ashraysinha6069** [comment]
i would like to work on it

**Comment by gauthamzz** [comment]
Assigned to you @ashraysinha6069

**Comment by ashraysinha6069** [comment]
i've sent the PR
