### ISSUE TITLE
Fix the loading of the website.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#20]
The website doesnt load sometimes properly. Only after refreshing only it works !

**Comment by falconis** [comment]
Any pointers as to what can be wrong?

**Comment by OrionStar25** [comment]
I'd like to work on this. :D

**Comment by Jigar3** [comment]
I would also like to work on this issue

**Comment by aswanthkoleri** [comment]
@OrionStar25  .You are assigned to this issue . :stuck_out_tongue:

**Comment by aswanthkoleri** [comment]
@OrionStar25  Try creating different vue.js script for each of the news.And then link it to the Index.html. And dont forget to use only one array in one VueJS script. This might increase the speed.As of now the fetching speed is low that's why the website doesn't load on the first time. You can refer to the console errors to solve it.I think solving the console errors is to fix this issue.

**Comment by aswanthkoleri** [comment]
This issue is solved along with #1  in the pull request #36
