### ISSUE TITLE
Use a loop to display the top 5 news 

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#32]
Use a loop to display the top 5 news instead of explicitly declaring all the divisions in the html.You may require the knowledge of loops in VueJS.

**Comment by Ace-Bansal** [comment]
I'll do it

**Comment by aswanthkoleri** [comment]
@Ace-Bansal Carry on !

**Comment by aswanthkoleri** [comment]
@Ace-Bansal  [Refer this ](https://stackoverflow.com/questions/44617484/vue-js-loop-via-v-for-x-times-in-a-range)

**Comment by Ace-Bansal** [comment]
Thank you!  😀
