### ISSUE TITLE
Star the repo to earn point ! 

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#34]
Comment your screenshots for verification ! :smile:

**Comment by dojutsu-user** [comment]
![capture](https://user-images.githubusercontent.com/29149191/34820256-07f6ef32-f6e6-11e7-95a8-8446f7e64fc3.PNG)

**Comment by Esha23** [comment]
![screenshot-2018-1-11 star the repo to earn point issue 34 aswanthkoleri opennews](https://user-images.githubusercontent.com/35305010/34823062-155bbff0-f6ef-11e7-94ce-934db90bcc2b.png)

**Comment by surasnayak** [comment]
Done!
![untitled1](https://user-images.githubusercontent.com/21239888/34823170-7aeb6d34-f6ef-11e7-8bbd-302c15201c51.png)

**Comment by helios1101** [comment]
![capture6](https://user-images.githubusercontent.com/26597930/34824462-8afe218a-f6f4-11e7-8a19-c42c0b50e32a.JPG)

**Comment by AK-007** [comment]
![screenshot 51](https://user-images.githubusercontent.com/26346816/34828075-55e3e97c-f702-11e7-92c5-e3566047b940.png)

**Comment by GOVINDDIXIT** [comment]
![capturea](https://user-images.githubusercontent.com/32304546/34829260-187a4014-f706-11e7-939b-00539820181f.PNG)

**Comment by abhishhh1** [comment]
![screenshot 4](https://user-images.githubusercontent.com/31480124/34829346-70969946-f706-11e7-8e1a-dc3de7c17a0e.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34829371-85f182e2-f706-11e7-8125-736ac59d2e9c.png)

**Comment by aadixiiita** [comment]
![screenshot from 2018-01-11 19-41-48](https://user-images.githubusercontent.com/34688457/34829697-8bc7c93c-f707-11e7-9b10-b0ec4f2dc553.png)

**Comment by Ace-Bansal** [comment]
![screenshot 19](https://user-images.githubusercontent.com/34866483/34829691-87a7841e-f707-11e7-88b9-abbed3a71082.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34830013-9222457c-f708-11e7-85a7-f6f5d43d8e90.png)

**Comment by Panda2498** [comment]
![opennews](https://user-images.githubusercontent.com/34282889/34831294-9755e40a-f70c-11e7-9081-d53141ebdfb4.PNG)

**Comment by masterchef2209** [comment]
![1](https://user-images.githubusercontent.com/27916352/34833764-326b369e-f716-11e7-9597-adb236f0444e.jpg)

**Comment by swaager** [comment]
![awse](https://user-images.githubusercontent.com/29673845/34833918-955bd8bc-f716-11e7-9192-06fc54876ded.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-11 22-02-26](https://user-images.githubusercontent.com/32292953/34835611-498c0556-f71b-11e7-8ca4-386b767e26b2.png)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34839535-e9174dcc-f727-11e7-8e23-4e0db1832818.png)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-02-18](https://user-images.githubusercontent.com/26206171/34840736-e55a0cf2-f72b-11e7-8c2e-b03ff226db19.png)

**Comment by adiagg2000** [comment]
![screenshot 37](https://user-images.githubusercontent.com/33027339/34843695-35aa94b6-f735-11e7-8d8f-6e9daade2a8f.png)

**Comment by ProBeta1** [comment]
![screenshot-2018-1-12 aswanthkoleri opennews](https://user-images.githubusercontent.com/33081197/34843906-d4de6936-f735-11e7-9377-73fc8c3e6b3f.png)

**Comment by gau1rav** [comment]
![starred3](https://user-images.githubusercontent.com/34263673/34847426-55ef4ae4-f741-11e7-99f9-d8f0ab9183b6.png)

**Comment by OrionStar25** [comment]
![screenshot from 2018-01-12 02-38-56](https://user-images.githubusercontent.com/28835849/34847515-9549bb3e-f741-11e7-96f9-f1bdfa7b4ebc.png)

**Comment by Jigar3** [comment]
![screenshot_2018-01-12-02-55-43-191_com android chrome](https://user-images.githubusercontent.com/32068121/34848284-3a910d98-f744-11e7-97f2-64672c59fe13.png)

**Comment by cuz789** [comment]
![2018-01-12 3](https://user-images.githubusercontent.com/35086901/34849828-b88db9a8-f749-11e7-8d71-9d1d692d2c86.png)

**Comment by Tlazypanda** [comment]
![screenshot_2018-01-12-03-54-39](https://user-images.githubusercontent.com/33183263/34850555-54f3119c-f74c-11e7-9812-ac02d9c59ed9.png)

**Comment by vvvinamer** [comment]
![screenshot 38](https://user-images.githubusercontent.com/35339278/34869067-ca034128-f7ab-11e7-9608-3af22219aa27.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-13 change background color issue 43 opencode18 opennews](https://user-images.githubusercontent.com/28799332/34892299-c4fb07bc-f7fe-11e7-82a0-6cf7b956b4a0.png)

**Comment by hacker1x1x1** [comment]
![screenshot_20180113-014114](https://user-images.githubusercontent.com/34509429/34893390-f6d8205e-f802-11e7-8f32-bcefa2613246.jpg)

**Comment by anandwana001** [comment]
![screenshot_2018-01-14-03-41-19-068_com android chrome](https://user-images.githubusercontent.com/25057618/34910498-cdb7606a-f8dc-11e7-9865-2d9a67afdc04.png)

**Comment by ashish4321** [comment]
![screen shot 2018-01-14 at 13 04 46](https://user-images.githubusercontent.com/25305613/34913801-98bb322e-f92c-11e7-95b9-69614fd1ec90.png)

**Comment by falconis** [comment]
![star32](https://user-images.githubusercontent.com/30634978/36046422-e1efcfe0-0dfe-11e8-9054-c717a802e875.png)
