### ISSUE TITLE
Scroll Back to Top button

### ISSUE THREAD

**Issue by anandwana001** [opencode18/OpenNews#48]
I would like to create a scroll back to top button.

**Comment by hacker1x1x1** [comment]
Can I do this?

**Comment by aswanthkoleri** [comment]
@hacker1x1x1 yes you can.

**Comment by anandwana001** [comment]
I create this issue as I am working on it and same I mention above.

**Comment by anandwana001** [comment]
Mentors please assign the issue.

**Comment by mubaris** [comment]
@aswanthkoleri I think it should be assigned to @anandwana001

**Comment by aswanthkoleri** [comment]
@anandwana001  Whats the status ?

**Comment by anandwana001** [comment]
I'll send PR by today
