### ISSUE TITLE
Add a loader for the website.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#5]

**Comment by arpitmisraw** [comment]
I would like to work on this.

**Comment by aswanthkoleri** [comment]
@arpitmisraw  you can continue !

**Comment by aswanthkoleri** [comment]
@arpitmisraw what is the status ! Or this issue goes to someone else !

**Comment by ananya-agrawal** [comment]
will like to take this

**Comment by aswanthkoleri** [comment]
@ananya-agrawal This is assigned to you.

**Comment by falconis** [comment]
Can I work on this if no one else is working?

**Comment by ashraysinha6069** [comment]
i would like to work on this issue
