### ISSUE TITLE
Add a fork Ribbon in the corner.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#52]

**Comment by shivhek25** [comment]
https://github.com/blog/273-github-ribbons

Is this the ribbon that you are talking about ? @aswanthkoleri

**Comment by Esha23** [comment]
I would like to work on it

**Comment by aswanthkoleri** [comment]
@shivhek25  Are you interestd ?

**Comment by aswanthkoleri** [comment]
@shivhek25 Yes, I'm talking about those ribbons

**Comment by ashraysinha6069** [comment]
i would like to work on this issue

**Comment by aswanthkoleri** [comment]
@Esha23 You may continue

**Comment by swaager** [comment]
i want to take this , if no one is working on it.

**Comment by shivhek25** [comment]
I am ready to work on this.

**Comment by shivhek25** [comment]
PR created. Please check.
