### ISSUE TITLE
Place the Read more button inside the Card.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#60]
The read more button does'nt look good. Place it inside the card.

**Comment by aayushjoglekar** [comment]
I'll do this.

**Comment by aswanthkoleri** [comment]
@aayushjoglekar continue

**Comment by mahek5** [comment]
Has this issue been solved? I want to work on this.

**Comment by gauthamzz** [comment]
Yeah . Sorry for not closing this . You can find more issues at any of our repo
