### ISSUE TITLE
Fix button color of " Read more " on click.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenNews#9]

**Comment by AK-007** [comment]
@aswanthkoleri I would like to work on this issue.Do you want the colour to be same when when it is clicked?

**Comment by aswanthkoleri** [comment]
@AK-007 You already have issues pending !

**Comment by AK-007** [comment]
But,both of my PR got merged.

**Comment by hacker1x1x1** [comment]
can i contribute?

**Comment by hacker1x1x1** [comment]
But you see... I requested before you😇

**Comment by Tachyon01** [comment]
I want to solve this issue

**Comment by AK-007** [comment]
@aswanthkoleri Do you want to stop the button colour from changing to green on clicking?

**Comment by Esha23** [comment]
I also want to solve this issue.

**Comment by aswanthkoleri** [comment]
@hacker1x1x1 You may continue !
